language: rust
rust:
  - 1.36.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

script:
  - ./capstone-rs/ci/test.sh

before_script:
  - rustup update "$TRAVIS_RUST_VERSION"

cache:
  cargo: true
  directories:
    - kcov-install
before_cache:
  - rm -rf target/cov "$TRAVIS_HOME/.cargo/registry/src"

matrix:
  # Clear the whole matrix
  exclude:
    - os: linux
    - os: osx
  # Add each target manually
  include:
    - os: linux
      rust: 1.36.0
    - os: linux
      rust: stable
      env: JOB=valgrind-test
      addons:
        apt:
          packages:
            - valgrind
    - os: linux
      rust: beta
      env: JOB=valgrind-test
      addons:
        apt:
          packages:
            - valgrind
    - os: linux
      rust: nightly
      env: JOB=valgrind-test
      addons:
        apt:
          packages:
            - valgrind
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
    - os: linux
      rust: stable
      env: JOB=cov
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev

notifications:
  email: false
