[package]
name = "dfuzz-os"
version = "0.1.0"
authors = ["Hugh Wang <hghwng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
errno = "0.2"
procfs = "0.5"

log = "0.4"
failure = {version = "0.1", features = ["backtrace"]}

bitflags = "1.1"
num-traits = "0.2"
num-derive = "0.2"
